Repository meltano/sdk, pull requests merged in 2022-08, with the labels that each got.

#868 fix(taps): Update return type for `backoff_max_tries` to reflect it accepts a callable that returns an integer
  singer_sdk/streams/rest.py
Labels: Awaiting Action/Author, Community-Contributed PR

#923 ci: Limit test job concurrency
  .github/workflows/test.yml
Labels: CI/CD, valuestream/SDK

#941 chore: Update `poetry.lock` to Poetry 1.2 format
  .github/workflows/constraints.txt
  poetry.lock
Labels: deps
