Repository meltano/sdk, pull requests merged in 2022-09, with the labels that each got.

#829 feat(taps): Add checks for primary keys, replication keys and state partitioning keys to standard tap tests
  singer_sdk/testing.py
Labels: Awaiting Action/Author, Community-Contributed PR

#942 docs: Add docs preview links to PR description
  .github/workflows/pr-preview-links.yml
Labels: Documentation, CI/CD

#898 fix: Fix SQL type merging for pre-existing target tables
  singer_sdk/streams/sql.py
Labels: Community-Contributed PR

#826 chore(templates): Remove Poetry version pin for GitHub Actions
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/{% if cookiecutter.include_cicd_sample_template == 'GitHub' %}ci_workflow.yml{%endif%}
Labels: Community-Contributed PR
