Repository meltano/sdk, pull requests merged in 2022-06, with the labels that each got.

#678 SQL connector modular discover
  samples/sample_tap_bigquery/__init__.py
  singer_sdk/streams/sql.py
Labels: community-contributed mr

#679 chore: Add a test workflow
  .github/dependabot.yml
  .github/workflows/constraints.txt
  .github/workflows/test.yml
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tox.ini
Labels: internal

#691 ci: Enable external tests
  .github/workflows/test.yml
  README.md
  poetry.lock
  pyproject.toml
Labels: ci/cd, valuestream::sdk

#747 ci: Version bump
  .github/workflows/constraints.txt
  .github/workflows/release.yml
  .github/workflows/version_bump.yml
  .pre-commit-config.yaml
  README.md
  pyproject.toml
Labels: CI/CD
