Repository meltano/sdk, pull requests merged in 2024-10, with the labels that each got.

#2701 feat(mappers): Stream name can now be accessed in `__alias__` context of stream maps
  docs/stream_maps.md
  singer_sdk/mapper.py
  tests/core/test_mapper.py
  tests/snapshots/mapped_stream/aliased_stream_not_expr.jsonl
  tests/snapshots/mapped_stream/aliased_stream_quoted.jsonl
  tests/snapshots/mapped_stream/builtin_variable_stream_name_alias.jsonl
  tests/snapshots/mapped_stream/builtin_variable_stream_name_alias_expr.jsonl
Labels: Stream Maps, Needs Documentation

#2699 feat(mappers): Stream name can now be accessed in stream maps
  docs/stream_maps.md
  singer_sdk/mapper.py
  tests/core/test_mapper.py
  tests/snapshots/mapped_stream/builtin_variable_self.jsonl
  tests/snapshots/mapped_stream/builtin_variable_stream_name.jsonl
  tests/snapshots/mapped_stream/builtin_variable_underscore.jsonl
Labels: Stream Maps, Needs Documentation

#2637 feat: Environment variables are now parsed for boolean, integer, array and object setting values
  docs/implementation/cli.md
  poetry.lock
  singer_sdk/configuration/_dict_config.py
  tests/core/configuration/test_dict_config.py
Labels: Needs Documentation

#2730 feat: Added `SQLConnector.prepare_primary_key` for target to implement for custom table primary key adaptation
  singer_sdk/connectors/sql.py
  singer_sdk/testing/suites.py
  singer_sdk/testing/target_test_streams/pk_updates.singer
  singer_sdk/testing/target_tests.py
  tests/core/test_connector_sql.py
Labels: Needs Documentation, Release Highlight

#2727 fix: Object and array JSON types are now handled before primitive types when converting them to SQL types
  singer_sdk/typing.py
  tests/core/test_typing.py
Labels: SQL

#2736 packaging: Skip `simpleeval` 1.0.1
  poetry.lock
  pyproject.toml
Labels: Dependencies
