Repository meltano/sdk, pull requests merged in 2025-06, with the labels that each got.

#3075 test: Use snapshots to test message streams in sample target CSV tests
  pyproject.toml
  singer_sdk/testing/legacy.py
  tests/samples/snapshots/test_target_csv/test_countries_to_csv/singer.log
  tests/samples/snapshots/test_target_csv/test_countries_to_csv/tap.jsonl
  tests/samples/snapshots/test_target_csv/test_countries_to_csv/target.jsonl
  tests/samples/snapshots/test_target_csv/test_countries_to_csv_mapped/mapper.jsonl
  tests/samples/snapshots/test_target_csv/test_countries_to_csv_mapped/mapper.log
  tests/samples/snapshots/test_target_csv/test_countries_to_csv_mapped/tap.jsonl
  tests/samples/snapshots/test_target_csv/test_countries_to_csv_mapped/tap.log
  tests/samples/snapshots/test_target_csv/test_countries_to_csv_mapped/target.jsonl
  tests/samples/snapshots/test_target_csv/test_countries_to_csv_mapped/target.log
  tests/samples/snapshots/test_target_csv/test_fake_people_to_csv/singer.log
  tests/samples/snapshots/test_target_csv/test_fake_people_to_csv/tap.jsonl
  tests/samples/snapshots/test_target_csv/test_fake_people_to_csv/target.jsonl
  tests/samples/test_target_csv.py
Labels: kind/Tech Debt

#2620 feat(taps,targets): Interruption and termination signals are handled in taps and targets
  singer_sdk/plugin_base.py
  singer_sdk/tap_base.py
  singer_sdk/target_base.py
Labels: kind/Feature, Release Highlight, Type/Target, Type/Tap

#3087 feat: Honor `<APP_NAME>_LOGLEVEL` and `LOGLEVEL` environment variables across all default logging
  singer_sdk/_logging.py
  singer_sdk/metrics.py
  singer_sdk/plugin_base.py
Labels: Logging

#3048 fix(targets): Avoid emitting message "No schema for record field." when "additionalProperties" is set to true in stream schema
  singer_sdk/sinks/core.py
  tests/core/sinks/test_validation.py
Labels: Community-Contributed PR, Type/Target

#3091 fix: Correctly resolve JSON schema references when mulitple properties use the same reference
  singer_sdk/singerlib/schema.py
  tests/singerlib/test_schema.py
Labels: Type/Tap

#3111 fix(taps): Ensure state progress markers in child streams are finalized
  singer_sdk/streams/core.py
  tests/core/snapshots/test_parent_child/test_child_deselected_parent/singer.jsonl
Labels: Type/Tap, Incremental Replication

#3109 test: Test unmapped properties warning still shows when no additional properties specified
  tests/core/test_typing.py
Labels: Awaiting Action/Author, Community-Contributed PR

#3114 fix: Centralize state writing to avoid emitting duplicate STATE messages
  singer_sdk/helpers/_state.py
  singer_sdk/streams/core.py
  singer_sdk/tap_base.py
  tests/core/snapshots/test_parent_child/test_child_deselected_parent/singer.jsonl
  tests/core/snapshots/test_parent_child/test_one_parent_many_children/singer.jsonl
  tests/core/snapshots/test_parent_child/test_parent_context_fields_in_child/singer.jsonl
  tests/samples/snapshots/test_target_csv/test_fake_people_to_csv/tap.jsonl
  tests/samples/snapshots/test_target_csv/test_fake_people_to_csv/target.jsonl
Labels: kind/Tech Debt, Type/Tap, Incremental Replication

#3124 chore: Use `nonlocal` to update stream metadata
  singer_sdk/singerlib/catalog.py
Labels: kind/Tech Debt

#3099 packaging: Remove some unused Python version markers
  pyproject.toml
  uv.lock
Labels: Dependencies

#3126 packaging: Require SQLAlchemy >= 2.0
  pyproject.toml
  uv.lock
Labels: Dependencies, SQL

#3127 fix: Ensure Singer SDK warnings are logged
  singer_sdk/plugin_base.py
Labels: kind/Tech Debt, Logging

#3145 fix: Handle logging configuration not found gracefully
  singer_sdk/_logging.py
Labels: Logging

#3147 fix(templates): Run mypy in templates inside of a virtualenv including the package
  .github/workflows/cookiecutter-e2e.yml
  cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/build.yml
  cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/test.yml
  cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
  cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/pyproject.toml
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/build.yml
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/test.yml
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/sql-client.py
  cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/test.yml
  cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml
  cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
  noxfile.py
Labels: Cookiecutter
