Repository meltano/sdk, pull requests merged in 2025-01, with the labels that each got.

#2407 packaging: Use Poetry support for PEP 621
  .pre-commit-config.yaml
  noxfile.py
  poetry.lock
  pyproject.toml
Labels: Dependencies

#2829 feat(targets): Support a `x-sql-datatype` JSON Schema annotation to let targets customize SQL type handling
  docs/guides/sql-target.md
  singer_sdk/_singerlib/schema.py
  singer_sdk/connectors/sql.py
  tests/core/test_connector_sql.py
Labels: SQL, Type/Target

#2820 chore: Update templates
  .github/dependabot.yml
  .github/workflows/api-changes.yml
  .github/workflows/cookiecutter-e2e.yml
  .github/workflows/resources/requirements.txt
  .github/workflows/test.yml
  .pre-commit-config.yaml
  cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/build.yml
  cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
  cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/pyproject.toml
  cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/tox.ini
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/build.yml
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/README.md
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/tox.ini
  cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/build.yml
  cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml
  cookiecutter/target-template/{{cookiecutter.target_id}}/README.md
  cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
  cookiecutter/target-template/{{cookiecutter.target_id}}/tox.ini
Labels: Cookiecutter

#2844 fix: Avoid write empty state
  singer_sdk/streams/core.py
  singer_sdk/tap_base.py
  tests/core/test_parent_child.py
  tests/samples/test_tap_countries.py
  tests/samples/test_target_sqlite.py
  tests/snapshots/mapped_stream/aliased_stream.jsonl
  tests/snapshots/mapped_stream/aliased_stream_batch.jsonl
  tests/snapshots/mapped_stream/aliased_stream_not_expr.jsonl
  tests/snapshots/mapped_stream/aliased_stream_quoted.jsonl
  tests/snapshots/mapped_stream/builtin_variable_self.jsonl
  tests/snapshots/mapped_stream/builtin_variable_stream_name.jsonl
  tests/snapshots/mapped_stream/builtin_variable_stream_name_alias.jsonl
  tests/snapshots/mapped_stream/builtin_variable_stream_name_alias_expr.jsonl
  tests/snapshots/mapped_stream/builtin_variable_underscore.jsonl
  tests/snapshots/mapped_stream/changed_key_properties.jsonl
  tests/snapshots/mapped_stream/dates.jsonl
  tests/snapshots/mapped_stream/drop_property.jsonl
  tests/snapshots/mapped_stream/drop_property_null_string.jsonl
  tests/snapshots/mapped_stream/fake_credit_card_number.jsonl
  tests/snapshots/mapped_stream/fake_email_seed_class.jsonl
  tests/snapshots/mapped_stream/fake_email_seed_instance.jsonl
  tests/snapshots/mapped_stream/flatten_all.jsonl
  tests/snapshots/mapped_stream/flatten_depth_0.jsonl
  tests/snapshots/mapped_stream/flatten_depth_1.jsonl
  tests/snapshots/mapped_stream/keep_all_fields.jsonl
  tests/snapshots/mapped_stream/map_and_flatten.jsonl
  tests/snapshots/mapped_stream/no_map.jsonl
  tests/snapshots/mapped_stream/non_pk_passthrough.jsonl
  tests/snapshots/mapped_stream/only_mapped_fields.jsonl
  tests/snapshots/mapped_stream/only_mapped_fields_null_string.jsonl
  tests/snapshots/mapped_stream/record_to_column.jsonl
  tests/snapshots/mapped_stream/sourced_stream_1.jsonl
  tests/snapshots/mapped_stream/sourced_stream_1_null_string.jsonl
  tests/snapshots/mapped_stream/sourced_stream_2.jsonl
Labels: Community-Contributed PR

#2852 packaging: Remove `urllib3` constraint
  pyproject.toml
  uv.lock
Labels: Dependencies

#2861 docs: Document plugin development with uv and how to migrate existing ones
  docs/CONTRIBUTING.md
  docs/cli_commands.md
  docs/dev_guide.md
  docs/faq.md
  docs/guides/custom-clis.md
  docs/guides/index.md
  docs/guides/migrate-to-uv.md
  docs/guides/porting.md
  docs/implementation/logging.md
  docs/index.md_
  docs/python_tips.md
Labels: Documentation

#2862 fix(templates): Include package license metadata conditionally in templates
  cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/pyproject.toml
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
  cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
  e2e-tests/cookiecutters/tap-no-license.json
Labels: Community-Contributed PR

#2864 chore: Fix local SDK use in cookiecutter tests
  .github/workflows/cookiecutter-e2e.yml
  noxfile.py
Labels: Cookiecutter
