Repository meltano/sdk, pull requests merged in 2025-03, with the labels that each got.

#2786 feat(taps,targets): Support the `x-singer.decimal` JSON Schema extension
  docs/guides/sql-tap.md
  docs/guides/sql-target.md
  singer_sdk/connectors/sql.py
  singer_sdk/helpers/capabilities.py
  singer_sdk/tap_base.py
  singer_sdk/typing.py
  tests/core/test_connector_sql.py
Labels: SQL, Release Highlight, Type/Target, Type/Tap

#2902 chore: GitHub Actions Security Analysis with zizmor 🌈
  .github/workflows/api-changes.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/codspeed.yml
  .github/workflows/cookiecutter-e2e.yml
  .github/workflows/dependency-review.yml
  .github/workflows/pr-preview-links.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/version_bump.yml
  .github/workflows/zizmor.yml
  zizmor.yml
Labels: CI/CD, security

#2903 fix: Don't warn about catalog schema not matching records if there are no records available to test against
  singer_sdk/testing/runners.py
  singer_sdk/testing/tap_tests.py
  singer_sdk/testing/templates.py
  tests/samples/test_tap_csv.py
Labels: Community-Contributed PR, testing

#2906 fix: Suppress `No records were available to test` warnings when empty stream is ignored
  singer_sdk/testing/templates.py
Labels: Community-Contributed PR

#2541 feat: Implement Singer msgspec encoding
  docs/dev_guide.md
  docs/guides/index.md
  docs/guides/performance.md
  noxfile.py
  pyproject.toml
  requirements/requirements.codspeed.txt
  requirements/requirements.txt
  samples/sample_tap_countries/countries_tap.py
  samples/sample_tap_sqlite/__init__.py
  samples/sample_target_sqlite/__init__.py
  singer_sdk/contrib/msgspec.py
  singer_sdk/mapper_base.py
  singer_sdk/plugin_base.py
  singer_sdk/singerlib/encoding/base.py
  singer_sdk/tap_base.py
  singer_sdk/target_base.py
  singer_sdk/testing/legacy.py
  singer_sdk/testing/runners.py
  tests/core/test_io.py
  tests/samples/test_tap_countries.py
  tests/singerlib/__init__.py
  tests/singerlib/encoding/conftest.py
  tests/singerlib/encoding/test_msgspec.py
  tests/singerlib/encoding/test_simple.py
  tests/singerlib/test_catalog.py
  tests/singerlib/test_messages.py
  tests/singerlib/test_schema.py
  tests/singerlib/test_utils.py
  uv.lock
Labels: performance, Needs Documentation, Release Highlight

#2908 feat(taps): Include response content when HTTP request fails fatally in REST streams
  singer_sdk/streams/rest.py
  tests/core/rest/test_failure.py
Labels: Type/Tap

#2789 feat: Conditionally required settings
  singer_sdk/typing.py
  tests/core/test_jsonschema_helpers.py
Labels: configuration

#2911 chore(deps): Avoid using requirements.txt files and rely on uv.lock
  .github/workflows/codspeed.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  noxfile.py
  pyproject.toml
  requirements/requirements.codspeed.txt
  requirements/requirements.docs.txt
  requirements/requirements.test.txt
  requirements/requirements.txt
  requirements/requirements.typing.txt
  uv.lock
Labels: Dependencies

#2885 feat(templates): Update tap, target and mapper dependencies in templates
  cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/test.yml
  cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
  cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/pyproject.toml
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/test.yml
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
  cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
  cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/test.yml
  cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml
  cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
Labels: Dependencies, Cookiecutter

#2932 fix: Ensure stream schema is overridden by the input catalog
  singer_sdk/streams/core.py
Labels: Type/Tap
